// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import FacultyController from "./faculty_controller"
application.register("faculty", FacultyController)

import GroupsController from "./groups_controller"
application.register("groups", GroupsController)

import AcademicPeriodController from "./academic_period_controller"
application.register("academic-period", AcademicPeriodController)

import ResizableController from "./teacher_search_controller"
application.register("teacher-search", ResizableController)

import TeacherSearchController from "./resizable_controller"
application.register("resizable", TeacherSearchController)

import TeacherSelectionController from "./teacher_selection_controller"
application.register("teacher-selection", TeacherSelectionController)

import ClassroomSelectionController from "./classroom_selection_controller"
application.register("classroom-selection", ClassroomSelectionController)

import ClassroomSearchController from "./classroom_search_controller"
application.register("classroom-search", ClassroomSearchController)


import DefaultScheduleController from "./schedule/default_schedule_controller"
application.register("default-schedule", DefaultScheduleController)


import TransferScheduleController from "./schedule/transfers/transfer_schedule_controller"
application.register("transfer-schedule", TransferScheduleController)

import DateChangeController from "./schedule/transfers/date_change_controller"
application.register("date-change", DateChangeController)

import TransferScheduleCardController from "./schedule/transfers/transfer_schedule_card_controller"
application.register("transfer-schedule-card", TransferScheduleCardController)

import TransferDropzoneController from "./schedule/transfers/transfer_dropzone_controller"
application.register("transfer-dropzone", TransferDropzoneController)

import TrashBinController from "./schedule/transfers/trash_bin_controller"
application.register("trash-bin", TrashBinController)

import TransferChangesController from "./schedule/transfers/transfer_changes_controller"
application.register("transfer-changes", TransferChangesController)

import TransfersTeacherSelectionController from "./schedule/transfers/transfers_teacher_selection_controller"
application.register("transfers-teacher-selection", TransfersTeacherSelectionController)

import TransfersClassroomSelectionController from "./schedule/transfers/transfers_classroom_selection_controller"
application.register("transfers-classroom-selection", TransfersClassroomSelectionController)

import UnsavedChangesController from "./schedule/unsaved_changes_controller"
application.register("unsaved-changes", UnsavedChangesController)

import LectureScheduleCardsController from "./schedule/lecture/lecture_schedule_cards"
application.register("lecture-schedule-cards", LectureScheduleCardsController)

import TestScheduleCardsController from "./schedule/test_schedule/test_schedule_cards"
application.register("test-schedule-cards", TestScheduleCardsController)

import ExamScheduleController from "./schedule/exam/exam_schedule_controller"
application.register("exam-schedule", ExamScheduleController)
